// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTWdSDpaWfA0wyPBVToa3WxPRUDcU_QvE',
    appId: '1:860165090066:web:2cf6a01cf8ad08c4bd21cb',
    messagingSenderId: '860165090066',
    projectId: 'tyrasoft-c8a94',
    authDomain: 'tyrasoft-c8a94.firebaseapp.com',
    storageBucket: 'tyrasoft-c8a94.appspot.com',
    measurementId: 'G-NSDFVXNMFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgzbSf1WTloyCVN-rjsdd3sx3c4JLCAn0',
    appId: '1:860165090066:android:3d69b7588dbe8615bd21cb',
    messagingSenderId: '860165090066',
    projectId: 'tyrasoft-c8a94',
    storageBucket: 'tyrasoft-c8a94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZYReu7OJV6RN_afeK7RFVnZoXamNbMIM',
    appId: '1:860165090066:ios:afb36b4d05a7d315bd21cb',
    messagingSenderId: '860165090066',
    projectId: 'tyrasoft-c8a94',
    storageBucket: 'tyrasoft-c8a94.appspot.com',
    iosClientId: '860165090066-jdafsu7f0cl0b3pupae0abqn1naii38g.apps.googleusercontent.com',
    iosBundleId: 'com.tyrasoft.tyrasoftAttendance',
  );
}
